// Staging deploys the same build as production, so what tells the two apart — the icon in a tab,
// on a home screen and in a dock, and the name an install lands under — is rewritten on the way
// out rather than built in. The staging artwork ships in both builds and is generated by
// scripts/make-staging-icons.mjs; production never takes any branch in this file.

// Production icon path -> its staging counterpart. The shell and the landing page write these
// absolute, the web manifest relative, so the leading slash is left out and both forms match.
const ICONS = new Map([
  ['favicon-32-v3.png', 'icons/staging/favicon-32.png'],
  ['favicon-16-v3.png', 'icons/staging/favicon-16.png'],
  ['icons/apple-touch-icon.png', 'icons/staging/apple-touch-icon.png'],
  ['icons/icon-192-v2.png', 'icons/staging/icon-192.png'],
  ['icons/icon-512-v2.png', 'icons/staging/icon-512.png'],
  ['icons/icon-512-maskable-v2.png', 'icons/staging/icon-512-maskable.png'],
]);

// The name iOS writes under a home-screen icon, which comes from this tag rather than the manifest.
const IOS_TITLE = 'name="apple-mobile-web-app-title" content="sutamaya"';

// The staging deployment's two hostnames, declared as `routes` in wrangler.jsonc's staging env.
export const STAGING_APP_HOST = 'app.staging.sutamaya.org';
export const STAGING_MARKETING_HOST = 'staging.sutamaya.org';

// Whether a request is on the staging deployment. The hostname rather than a var, so the Worker,
// the client (web/src/lib/buildInfo.ts) and the tests all decide it the same way.
export function isStaging(hostname) {
  return hostname === STAGING_APP_HOST || hostname === STAGING_MARKETING_HOST;
}

// Returns HTML — the app shell or the landing page — with its icons and iOS name pointed at
// staging's.
export function brandHtml(html) {
  let out = html;
  for (const [from, to] of ICONS) out = out.replaceAll(from, to);
  return out.replaceAll(IOS_TITLE, IOS_TITLE.replace('sutamaya', 'sutamaya staging'));
}

// Returns the web manifest carrying the staging icons and name, so an install from staging sits
// beside a production install rather than looking like it.
export async function brandManifest(res) {
  const manifest = await res.json();
  return new Response(
    JSON.stringify({
      ...manifest,
      name: 'sutamaya staging',
      short_name: 'staging',
      icons: manifest.icons.map((icon) => ({ ...icon, src: ICONS.get(icon.src) ?? icon.src })),
    }),
    { headers: { 'Content-Type': 'application/manifest+json' } }
  );
}

// Returns an asset response with brandHtml applied to its body. Content-Length and ETag are
// dropped rather than recalculated: the body they described is not the one being sent.
export async function brandHtmlResponse(res) {
  const headers = new Headers(res.headers);
  headers.delete('content-length');
  headers.delete('etag');
  return new Response(brandHtml(await res.text()), { status: res.status, headers });
}
