#!/usr/bin/env node
// Reads /data (SuttaCentral-style Bilara JSON) and emits web/public/data/{corpus.json,dictionary.json,text/*.json}.
// See data/README.md for the raw data model, and CLAUDE.md for the browse-tree rules this encodes.

import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import {
  NIKAYA_META, AN_BOOK_NAMES, KN_BOOKS, SN_GROUPS, REF_ABBR, RESTATED_CHAPTERS,
  formatRef, stripTitlePrefix, flattenLeaves, findChapterNodes, findNodeByKey, findLeafGroups, rangeNote, chapterSpanNote,
  headerTitle, buildBodySegments,
} from './lib/collections.js';
import { splitPaliWords, stripPunct, lookupWord, shardFor } from './lib/paliWords.js';
import { red, green, bold, dim } from './lib/dataSync.js';

// The build is a long, quiet wall of counts, and the one thing anyone needs to spot in it is a
// failure — so a failure gets the only red in the output, and never a bare stack trace. `step` is
// the heading of a phase, `detail` its counts, and `ok` the checks that had to pass.
const step = (text) => console.log(bold(text));
const detail = (text) => console.log(dim(`  ${text}`));
const ok = (text) => console.log(`  ${green('✓')} ${text}`);
process.on('uncaughtException', (err) => {
  console.error(`\n  ${red('✗ build:corpus failed')}\n\n${err.message.replace(/^/gm, '  ')}\n`);
  process.exit(1);
});

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const DATA = path.join(ROOT, 'data');
// data/sujato/ holds Bhikkhu Sujato's pristine upstream English; data/sujato.post/ is that same tree with
// this app's editorial rules applied (see docs/retranslation.md) — the corpus is
// always built from the post-processed tree, generated by `npm run update-data post` (also run
// automatically as part of `npm run build:corpus`, since a fresh clone has no sujato.post/ yet).
const SUJATO = path.join(DATA, 'sujato.post');
// The build wipes and rewrites this directory, so build-corpus.counts.test.js points it at a
// temporary one: a test run has no business deleting the corpus a dev server is serving, and two
// builds racing over the same tree is what made that test intermittently fail.
const OUT = process.env.CORPUS_OUT || path.join(ROOT, 'web', 'public', 'data');
const OUT_TEXT = path.join(OUT, 'text');
const OUT_SHARDS = path.join(OUT, 'text-shards');

function readJSON(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

// Truncated to 16 hex chars everywhere it's used — these are change detectors, not security
// digests, and they travel in corpus.json and localStorage.
function sha256(s) {
  return createHash('sha256').update(s).digest('hex').slice(0, 16);
}
// Names the collection and expected path on failure — a bare ENOENT/JSON-parse stack trace here
// otherwise doesn't say which of the 25+ loadTree() calls (one per nikaya/KN book) actually
// failed.
function loadTree(id) {
  const treePath = path.join(DATA, 'tree', `${id}-tree.json`);
  try {
    return readJSON(treePath)[id];
  } catch (err) {
    throw new Error(`Failed to load tree for collection "${id}" from ${treePath}: ${err.message}`);
  }
}

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith('.json')) out.push(full);
  }
}
// `hint` covers the one case with an actual fix (data/html/ never fetched at all — see
// fetch-html-structure.mjs) — a merely-incomplete directory (some but not all files present)
// already degrades gracefully per-file elsewhere (see roleFor's own comment), this is only about
// the directory not existing at all.
function buildFileIndex(dir, hint) {
  if (!fs.existsSync(dir)) {
    throw new Error(`Missing data directory: ${dir}${hint ? ` — ${hint}` : ''}`);
  }
  const files = [];
  walk(dir, files);
  const index = new Map();
  for (const f of files) index.set(path.basename(f).split('_')[0], f);
  return index;
}

function buildNameIndex(filePath) {
  const map = new Map();
  if (!fs.existsSync(filePath)) return map;
  for (const [key, value] of Object.entries(readJSON(filePath))) {
    const afterColon = key.slice(key.indexOf(':') + 1);
    const dot = afterColon.indexOf('.');
    const refUid = dot === -1 ? afterColon : afterColon.slice(dot + 1);
    map.set(refUid, value.trim());
  }
  return map;
}
function buildBlurbIndex(filePath) {
  const map = new Map();
  if (!fs.existsSync(filePath)) return map;
  for (const [key, value] of Object.entries(readJSON(filePath))) {
    map.set(key.slice(key.indexOf(':') + 1), value.trim());
  }
  return map;
}

// Blurbs carry the same inline HTML a translator note does — mostly `<i lang='pi'>` around a Pali
// term. A group's blurb renders as HTML in ListPane and keeps it; a sutta's is drawn as plain text
// inside a search-highlighted row, so its markup would show as literal tags.
function stripTags(html) {
  return html.replace(/<[^>]+>/g, '');
}

function loadSegMap(filePath) {
  if (!filePath || !fs.existsSync(filePath)) return new Map();
  return new Map(Object.entries(readJSON(filePath)));
}

const sujatoManifest = readJSON(path.join(DATA, 'manifest.json'));

step('Indexing source files…');
const paliFiles = buildFileIndex(path.join(DATA, 'pali', 'sutta'));
const sujatoFiles = buildFileIndex(path.join(SUJATO, 'sutta'), 'run `npm run update-data post` first');
const htmlFiles = buildFileIndex(path.join(DATA, 'html', 'pli', 'ms', 'sutta'), 'run `node scripts/fetch-html-structure.mjs` first');
const notesFiles = buildFileIndex(path.join(SUJATO, 'notes'));
detail(
  `${paliFiles.size} pali files, ${sujatoFiles.size} sujato files, ${htmlFiles.size} html structure files, ${notesFiles.size} note files`
);

const nameIndexCache = new Map();
function nameIndexFor(collection) {
  if (nameIndexCache.has(collection)) return nameIndexCache.get(collection);
  const idx = {
    pali: buildNameIndex(path.join(DATA, 'pali', 'name', `${collection}-name_root-misc-site.json`)),
    en: buildNameIndex(path.join(SUJATO, 'name', `${collection}-name_translation-en-sujato.json`)),
  };
  nameIndexCache.set(collection, idx);
  return idx;
}
const blurbIndexCache = new Map();
function blurbIndexFor(collection) {
  if (blurbIndexCache.has(collection)) return blurbIndexCache.get(collection);
  const idx = buildBlurbIndex(path.join(SUJATO, 'blurb', `${collection}-blurbs_root-en.json`));
  blurbIndexCache.set(collection, idx);
  return idx;
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT_TEXT, { recursive: true });
fs.mkdirSync(OUT_SHARDS, { recursive: true });

const suttas = {};
let leafCount = 0;

// Every Pali token the reader can tap, gathered as the leaves are written. The dictionary section
// below trims DPD down to exactly what these can look up.
const tappableWords = new Set();

// Per-uid digests of exactly the bytes written to web/public/data/text/, folded into corpus.json's
// `dataVersion` below. That's what lets a client tell whether the sutta text it cached (under
// unversioned CacheFirst URLs — see CLAUDE.md's cache-staleness note) is still the text this build
// produces, and offer a re-download when it isn't.
const textDigests = new Map();

// Bulk offline download (Settings' "Download all suttas for offline") fetches these shard
// bundles instead of one request per sutta (~4000 across the whole canon) — see
// web/src/lib/offline.ts. Each shard is a hand-built JSON object literal (uid -> that uid's
// already-serialized segment array, string-concatenated rather than re-parsed/re-stringified)
// so building it costs no more than the per-uid file write already does. Flushed once the
// accumulated shard reaches SHARD_TARGET_BYTES, so shard count scales with corpus size rather
// than being fixed.
const SHARD_TARGET_BYTES = 1_000_000;
let shardBuf = [];
let shardBufBytes = 0;
let shardIndex = 0;
const shardManifest = [];

function flushShard() {
  if (shardBuf.length === 0) return;
  const file = `text-shards/${String(shardIndex).padStart(3, '0')}.json`;
  const body = `{${shardBuf.map(([uid, json]) => `${JSON.stringify(uid)}:${json}`).join(',')}}`;
  fs.writeFileSync(path.join(OUT, file), body);
  shardManifest.push({ file, bytes: Buffer.byteLength(body), uids: shardBuf.map(([uid]) => uid) });
  shardIndex += 1;
  shardBuf = [];
  shardBufBytes = 0;
}

function buildLeaf(uid, nodeId, collection) {
  const names = nameIndexFor(collection);
  const blurbs = blurbIndexFor(collection);
  const paliPath = paliFiles.get(uid);
  const sujatoPath = sujatoFiles.get(uid);
  const paliMap = loadSegMap(paliPath);
  const sujatoMap = loadSegMap(sujatoPath);
  const htmlMap = loadSegMap(htmlFiles.get(uid));
  const notesMap = loadSegMap(notesFiles.get(uid));
  const segs = buildBodySegments(paliMap, sujatoMap, htmlMap, notesMap);
  // Collected from the segments about to be written, not from data/pali, because these are the
  // exact strings SegmentedText renders as tappable `.pw` spans — see the dictionary section,
  // which ships only the headwords one of them can reach.
  for (const seg of segs) {
    if (seg.pali) for (const word of splitPaliWords(seg.pali)) tappableWords.add(word);
  }
  const words = segs.reduce((n, s) => n + (s.en ? s.en.split(/\s+/).filter(Boolean).length : 0), 0);
  const min = Math.max(1, Math.round(words / 200));

  const segsJson = JSON.stringify(
    segs.map(({ key, pali, en, role, headingLevel, note }) => ({
      key,
      pali,
      en,
      ...(role ? { role } : null),
      ...(headingLevel ? { headingLevel } : null),
      ...(note ? { note } : null),
    }))
  );
  fs.writeFileSync(path.join(OUT_TEXT, `${uid}.json`), segsJson);
  textDigests.set(uid, sha256(segsJson));

  shardBuf.push([uid, segsJson]);
  shardBufBytes += Buffer.byteLength(segsJson);
  if (shardBufBytes >= SHARD_TARGET_BYTES) flushShard();

  suttas[uid] = {
    ref: formatRef(uid),
    node: nodeId,
    en: headerTitle(sujatoMap, uid) || stripTitlePrefix(names.en.get(uid)) || formatRef(uid),
    pali: headerTitle(paliMap, uid) || names.pali.get(uid) || formatRef(uid),
    blurb: stripTags(blurbs.get(uid) || ''),
    min,
  };
  leafCount += 1;
}

// `chapterRef` may be a function of the category's own leaves, for a collection where each
// category restarts its numbering (Snp's and Ud's vaggas number their documents snp1.1…, ud3.1…,
// so there is no one ref shared across the book the way "SN35" is shared across its vaggas).
//
// Builds category rows (vagga-level) from findLeafGroups() output: one row per category, with
// its member leaves built and its `ref` set to the sutta-range note ("SN35.1–12", "MN1–10")
// rather than a plain ref, since a vagga has no canonical short ref of its own — the range is
// the most useful thing to show. `dotted` selects "{ref}.{n}" (sn/an) vs "{ref}{n}" (mn).
//
// Returns `{ rows, label }`: `rows` for the chapter's `chapters` array, and the label the
// chapter should carry.
//
// Exception: if there's exactly one category and it just restates the *chapter* it's the whole
// of, that extra nesting level is redundant, so it's skipped: `rows` comes back `undefined` (no
// `chapters` array, meaning the chapter itself becomes the leaf) and the leaves are tagged with
// `chapterKey` directly instead of the otherwise-identical category key. Two ways that happens —
// the labels come out identical (SN13 "Comprehension" holding a single "Comprehension" vagga),
// or the two levels were translated differently from the same Pali (RESTATED_CHAPTERS).
function buildCategoryRows(categories, collection, chapterKey, chapterLabel, chapterRef, dotted) {
  const names = nameIndexFor(collection);
  const blurbs = blurbIndexFor(collection);
  const meta = categories.map(({ key, leaves }) => {
    const paliName = names.pali.get(key);
    return { key, leaves, paliName, label: stripTitlePrefix(names.en.get(key)) || paliName || key };
  });
  if (meta.length === 1 && (meta[0].label === chapterLabel || chapterKey in RESTATED_CHAPTERS)) {
    meta[0].leaves.forEach((uid) => buildLeaf(uid, chapterKey, collection));
    return { rows: undefined, label: RESTATED_CHAPTERS[chapterKey] ?? chapterLabel };
  }
  const rows = meta.map(({ key, leaves, label, paliName }) => {
    leaves.forEach((uid) => buildLeaf(uid, key, collection));
    const blurb = blurbs.get(key);
    return {
      id: key,
      ref: rangeNote(typeof chapterRef === 'function' ? chapterRef(leaves) : chapterRef, leaves, dotted),
      label,
      sub: paliName,
      count: leaves.length,
      ...(blurb ? { blurb } : null),
    };
  });
  return { rows, label: chapterLabel };
}

// Builds one chapter row (sn1, an3, …) from a findChapterNodes() entry: its own ref/label/sub,
// its leaf count, and its vagga-level category rows underneath (buildCategoryRows, with any
// "fifty"/pannasaka wrapper already flattened away by findLeafGroups). Shared by AN (chapters
// sit directly under the nikaya) and SN (chapters sit one level down, under a super-vagga group)
// — the only thing SN's caller does differently is wrap the result in its own group row.
// `labelOverride` covers AN, whose chapter label ("Book of Ones") comes from a hardcoded name
// list rather than the corpus name-index SN's chapters resolve their label from.
function buildChapterRow({ key, node, leaves }, collection, dotted, labelOverride) {
  const names = nameIndexFor(collection);
  const chapterRef = formatRef(key);
  const paliName = names.pali.get(key);
  const chapterLabel = labelOverride ?? (stripTitlePrefix(names.en.get(key)) || paliName || chapterRef);
  const { rows, label } = buildCategoryRows(findLeafGroups(node), collection, key, chapterLabel, chapterRef, dotted);
  const blurb = blurbIndexFor(collection).get(key);
  return {
    id: key,
    ref: chapterRef,
    label,
    sub: paliName,
    count: leaves.length,
    ...(blurb ? { blurb } : null),
    chapters: rows,
  };
}

const nikayas = [];

// --- DN: its 3 vaggas, each holding its suttas directly (DN has no numbered-chapter layer of
// its own, so this is the same shape as MN) ---
{
  const { rows: categoryRows } = buildCategoryRows(findLeafGroups(loadTree('dn')), 'dn', 'dn', NIKAYA_META.dn.label, 'DN', false);
  nikayas.push({ id: 'dn', label: NIKAYA_META.dn.label, sub: NIKAYA_META.dn.sub, count: categoryRows.length, chapters: categoryRows });
  detail(`dn: ${categoryRows.length} categories, ${categoryRows.reduce((n, c) => n + c.count, 0)} suttas`);
}

// --- MN: vagga-level categories directly (MN has no numbered-chapter layer of its own), with
// its 3 "fifty" (pannasa) wrapper groups flattened away structurally ---
{
  const { rows: categoryRows } = buildCategoryRows(findLeafGroups(loadTree('mn')), 'mn', 'mn', NIKAYA_META.mn.label, 'MN', false);
  nikayas.push({ id: 'mn', label: NIKAYA_META.mn.label, sub: NIKAYA_META.mn.sub, count: categoryRows.length, chapters: categoryRows });
  detail(`mn: ${categoryRows.length} categories, ${categoryRows.reduce((n, c) => n + c.count, 0)} suttas`);
}

// --- SN: 5 super-vagga groups (Verses, Causation, …), each wrapping its sn1..sn56 chapters;
// each chapter further split into vagga-level categories, with any "fifty" (pannasaka)
// wrapper layer flattened away structurally (see findLeafGroups) rather than shown as a row.
{
  const tree = loadTree('sn');
  const names = nameIndexFor('sn');
  const blurbs = blurbIndexFor('sn');
  const groupRows = SN_GROUPS.map((group) => {
    const groupNode = findNodeByKey(tree, group.id);
    const chapterNodes = findChapterNodes(groupNode, /^sn\d+$/);
    chapterNodes.sort((a, b) => +a.key.slice(2) - +b.key.slice(2));
    const chapterRows = chapterNodes.map((c) => buildChapterRow(c, 'sn', true));
    const totalSuttas = chapterRows.reduce((n, c) => n + c.count, 0);
    return {
      id: group.id,
      ref: chapterSpanNote('SN', chapterRows[0].id, chapterRows[chapterRows.length - 1].id),
      label: group.label,
      sub: names.pali.get(group.id),
      count: totalSuttas,
      ...(blurbs.get(group.id) ? { blurb: blurbs.get(group.id) } : null),
      chapters: chapterRows,
    };
  });
  const totalChapters = groupRows.reduce((n, g) => n + g.chapters.length, 0);
  const totalSuttas = groupRows.reduce((n, g) => n + g.count, 0);
  nikayas.push({ id: 'sn', label: NIKAYA_META.sn.label, sub: NIKAYA_META.sn.sub, count: groupRows.length, chapters: groupRows });
  detail(`sn: ${groupRows.length} groups, ${totalChapters} chapters, ${totalSuttas} suttas`);
}

// --- AN: nipātas (an1 "Book of Ones", …), each split into vagga-level categories, with any
// "fifty" (pannasaka) wrapper layer flattened away structurally ---
{
  const chapters = findChapterNodes(loadTree('an'), /^an\d+$/);
  chapters.sort((a, b) => +a.key.slice(2) - +b.key.slice(2));
  const chapterRows = chapters.map((c, i) => buildChapterRow(c, 'an', true, `Book of ${AN_BOOK_NAMES[i] || `Book ${i + 1}`}`));
  nikayas.push({ id: 'an', label: NIKAYA_META.an.label, sub: NIKAYA_META.an.sub, count: chapterRows.length, chapters: chapterRows });
  detail(`an: ${chapterRows.length} chapters, ${chapterRows.reduce((n, c) => n + c.count, 0)} suttas`);
}

// --- KN: 6 curated books, flattened one level down to their leaf documents — except Snp and Ud,
// which keep their vagga rows (see KN_BOOKS) ---
{
  const chapterRows = KN_BOOKS.map((book) => {
    const tree = loadTree(book.id);
    const leaves = flattenLeaves(tree);
    const ref = REF_ABBR[book.id] || book.id.toUpperCase();
    const row = { id: book.id, ref, label: book.label, sub: book.pali, count: leaves.length };
    if (!book.vaggas) {
      leaves.forEach((uid) => buildLeaf(uid, book.id, book.id));
      return row;
    }
    // Each vagga's range badge takes its prefix from that vagga's own leaves ("Snp3.1–12"),
    // since the numbering restarts per vagga rather than running through the book.
    const vaggaRef = (vaggaLeaves) => formatRef(vaggaLeaves[0].slice(0, vaggaLeaves[0].lastIndexOf('.')));
    const { rows } = buildCategoryRows(findLeafGroups(tree), book.id, book.id, book.label, vaggaRef, true);
    return { ...row, chapters: rows };
  });
  nikayas.push({ id: 'kn', label: NIKAYA_META.kn.label, sub: NIKAYA_META.kn.sub, count: chapterRows.length, chapters: chapterRows });
  detail(`kn: ${chapterRows.length} books, ${chapterRows.reduce((n, c) => n + c.count, 0)} leaf documents`);
}

// --- Dictionary: flatten [{entry, definition:[...]}] into a headword-keyed object, trim it to the
// words this build actually emitted, then split it into range shards. A word tap needs one
// headword, so shipping the whole thing to answer one lookup is the wrong trade: the reader
// fetches only the shard covering the tapped word — see lib/dictionaryShards.ts.
//
// data/pli2en_dpd.json is already scoped to data/pali/ by update-data-dictionary.mjs, so the trim
// here mostly removes words that live in source files this build doesn't emit. It stays because
// it, and the verification pass under it, are what catch an import that went wrong — the reader's
// own tokenizer is the only authority on what a tap can ask for.
step('Building dictionary shards…');
const dictPath = path.join(DATA, 'pli2en_dpd.json');
const { dpdVersion, entries: dpdList } = readJSON(dictPath);
// A file predating update-data-dictionary.mjs is a bare array, and destructuring one gives an
// undefined `entries` and a crash three lines down that names neither the file nor the fix.
if (!Array.isArray(dpdList)) {
  throw new Error(
    `${dictPath} is not in the expected {dpdVersion, entries: [...]} shape.\n` +
      'Regenerate it: DPD_DB_PATH=/path/to/dpd.db npm run update-data dictionary'
  );
}
const dpdMap = {};
for (const { entry, definition } of dpdList) dpdMap[entry] = definition;

// Trim. DPD covers all of Pali, including the Apadāna, the commentaries and the Vinaya; a little
// over half its headwords are forms nothing in this corpus uses, and no tap can ever reach them.
// The keep-set is what lookupWord would consult for each token: the token itself and its lowercase
// form, since that is the pair it tries.
const reachable = new Set();
for (const raw of tappableWords) {
  const word = stripPunct(raw);
  if (!word) continue;
  reachable.add(word);
  reachable.add(word.toLowerCase());
}

const shipped = {};
for (const [key, def] of Object.entries(dpdMap)) {
  if (reachable.has(key)) shipped[key] = def;
}
const dpdJson = JSON.stringify(shipped);
detail(`${Object.keys(shipped).length} of ${dpdList.length} headwords reachable from this corpus`);

const DICT_SHARD_TARGET_BYTES = 256 * 1024;
// Shards are addressed by a lowercased key range, because lookupWord tries both the tapped word
// and its lowercase form; sorting and splitting on the same key is what keeps those two in one
// shard. Plain code-unit comparison, not localeCompare — lib/dictionaryShards.ts's binary search
// has to reproduce this ordering exactly, and only `<`/`>` is portable between the two.
const dictSortKey = (k) => k.toLowerCase();
const headwords = Object.keys(shipped).sort((a, b) => {
  const ka = dictSortKey(a);
  const kb = dictSortKey(b);
  if (ka !== kb) return ka < kb ? -1 : 1;
  return a < b ? -1 : a > b ? 1 : 0;
});

const dictShards = [];
let dictShardKeys = [];
let dictShardBytes = 0;
for (const key of headwords) {
  const bytes = JSON.stringify(key).length + JSON.stringify(shipped[key]).length + 2;
  // Never break a run of headwords sharing a sort key ("Buddha"/"buddha"): one lookup consults
  // both spellings, so a boundary falling between them would make the lowercase form unreachable.
  const canSplit = dictShardKeys.length > 0 && dictSortKey(dictShardKeys[dictShardKeys.length - 1]) !== dictSortKey(key);
  if (dictShardBytes + bytes > DICT_SHARD_TARGET_BYTES && canSplit) {
    dictShards.push(dictShardKeys);
    dictShardKeys = [];
    dictShardBytes = 0;
  }
  dictShardKeys.push(key);
  dictShardBytes += bytes;
}
if (dictShardKeys.length) dictShards.push(dictShardKeys);

fs.mkdirSync(path.join(OUT, 'dict-shards'), { recursive: true });
const dictManifest = dictShards.map((keys, i) => {
  const file = `dict-shards/${String(i).padStart(3, '0')}.json`;
  fs.writeFileSync(path.join(OUT, file), JSON.stringify(Object.fromEntries(keys.map((k) => [k, shipped[k]]))));
  return { file, first: dictSortKey(keys[0]), last: dictSortKey(keys[keys.length - 1]) };
});
fs.writeFileSync(path.join(OUT, 'dict-shards', 'manifest.json'), JSON.stringify({ shards: dictManifest }));
detail(`${headwords.length} headwords in ${dictShards.length} shards`);

// --- Verify the trim, by replaying it. Every word the reader can tap goes through the same
// manifest binary search and the same lookupWord the client runs, against the shard files just
// written, and the answer is compared with what data/pli2en_dpd.json gives for the same word. A
// headword dropped by a tokenizer that drifted out of step with web/src/lib/dictionary.ts, or
// stranded by a shard boundary, is otherwise invisible: the dock just says the word isn't there.
//
// It compares against that file, so it proves the shards say what the file says — not that the
// file itself is any good. Whether the import produced a sound dictionary is a separate question,
// and update-data-dictionary.mjs answers it there, against the file it replaces.
{
  const bodies = new Map();
  const shardBody = (file) => {
    if (!bodies.has(file)) bodies.set(file, readJSON(path.join(OUT, file)));
    return bodies.get(file);
  };
  const lost = [];
  for (const raw of tappableWords) {
    const before = lookupWord(dpdMap, raw);
    if (!before) continue;
    const key = stripPunct(raw).toLowerCase();
    const shard = key ? shardFor(dictManifest, key) : null;
    const after = shard ? lookupWord(shardBody(shard.file), raw) : null;
    if (!after) lost.push(`${raw} (was: ${before[0]})`);
    else if (after[0] !== before[0]) lost.push(`${raw} (was: ${before[0]}, now: ${after[0]})`);
  }
  if (lost.length) {
    throw new Error(
      `Dictionary trim lost ${lost.length} word(s) the reader can tap:\n  ${lost.slice(0, 20).join('\n  ')}` +
        (lost.length > 20 ? `\n  …and ${lost.length - 20} more` : '')
    );
  }
  ok(`verified: all ${tappableWords.size} tappable words resolve exactly as data/pli2en_dpd.json defines them`);

  // The coverage figure that describes what a reader meets: distinct words in the text this build
  // emitted, not words in the source data. Numerals are counted apart — verse and list numbering
  // are tappable, but nobody expects the dictionary to define "12".
  const forms = new Set();
  for (const raw of tappableWords) {
    const word = stripPunct(raw);
    if (word) forms.add(word);
  }
  let defined = 0;
  let numerals = 0;
  for (const form of forms) {
    if (shipped[form] || shipped[form.toLowerCase()]) defined += 1;
    else if (/^[0-9.–-]+$/.test(form)) numerals += 1;
  }
  ok(
    `coverage: ${defined} of ${forms.size} distinct words have a definition ` +
      dim(`(${forms.size - defined - numerals} have none, ${numerals} are numerals)`)
  );
}

// Both versions are emitted in corpus.json (precached and revisioned with the app shell, so a new
// build always delivers them) rather than derived from anything the client caches itself. They're
// kept apart because they're separately downloadable and wildly different sizes: a reworded
// sentence in one sutta must not prompt a ~20MB dictionary re-fetch. Sorting by uid makes
// dataVersion independent of directory-walk order, so an unchanged corpus rebuilds identically.
const dataVersion = sha256(
  [...textDigests]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([uid, digest]) => `${uid}:${digest}`)
    .join('\n')
);
const dictionaryVersion = sha256(dpdJson);

step('Writing the corpus…');
fs.writeFileSync(
  path.join(OUT, 'corpus.json'),
  JSON.stringify({ nikayas, suttas, sujatoCommit: sujatoManifest.sourceCommit, dataVersion, dictionaryVersion, dpdVersion })
);
detail(`corpus.json — ${leafCount} leaf documents, ${nikayas.length} nikāyas, data ${dataVersion}`);

flushShard();
const totalShardBytes = shardManifest.reduce((n, s) => n + s.bytes, 0);
fs.writeFileSync(
  path.join(OUT_SHARDS, 'manifest.json'),
  JSON.stringify({ totalBytes: totalShardBytes, totalUids: leafCount, shards: shardManifest })
);
detail(`${shardManifest.length} text shards (${(totalShardBytes / 1e6).toFixed(1)} MB) for offline bulk download`);

console.log(`\n  ${green('✓ build:corpus complete')}\n`);
