#!/usr/bin/env node
// Reads /data (SuttaCentral-style Bilara JSON) and emits web/public/data/{corpus.json,dictionary.json,text/*.json}.
// See data/README.md for the raw data model, and CLAUDE.md for the browse-tree rules this encodes.

import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import {
  NIKAYA_META, AN_BOOK_NAMES, KN_BOOKS, SN_GROUPS, REF_ABBR,
  formatRef, stripTitlePrefix, flattenLeaves, findChapterNodes, findNodeByKey, findLeafGroups, rangeNote, chapterSpanNote,
  headerTitle, buildBodySegments,
} from './lib/collections.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const DATA = path.join(ROOT, 'data');
// data/sujato/ holds Sujato's pristine upstream English; data/sujato.post/ is that same tree with
// this app's editorial rules applied (see docs/retranslation.md) — the corpus is
// always built from the post-processed tree, generated by `npm run update-data:post` (also run
// automatically as part of `npm run build:corpus`, since a fresh clone has no sujato.post/ yet).
const SUJATO = path.join(DATA, 'sujato.post');
const OUT = path.join(ROOT, 'web', 'public', 'data');
const OUT_TEXT = path.join(OUT, 'text');
const OUT_SHARDS = path.join(OUT, 'text-shards');

function readJSON(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

// Truncated to 16 hex chars everywhere it's used — these are change detectors, not security
// digests, and they travel in corpus.json and localStorage.
function sha256(s) {
  return createHash('sha256').update(s).digest('hex').slice(0, 16);
}
// Names the collection and expected path on failure — a bare ENOENT/JSON-parse stack trace here
// otherwise doesn't say which of the 25+ loadTree() calls (one per nikaya/KN book) actually
// failed.
function loadTree(id) {
  const treePath = path.join(DATA, 'tree', `${id}-tree.json`);
  try {
    return readJSON(treePath)[id];
  } catch (err) {
    throw new Error(`Failed to load tree for collection "${id}" from ${treePath}: ${err.message}`);
  }
}

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith('.json')) out.push(full);
  }
}
// `hint` covers the one case with an actual fix (data/html/ never fetched at all — see
// fetch-html-structure.mjs) — a merely-incomplete directory (some but not all files present)
// already degrades gracefully per-file elsewhere (see roleFor's own comment), this is only about
// the directory not existing at all.
function buildFileIndex(dir, hint) {
  if (!fs.existsSync(dir)) {
    throw new Error(`Missing data directory: ${dir}${hint ? ` — ${hint}` : ''}`);
  }
  const files = [];
  walk(dir, files);
  const index = new Map();
  for (const f of files) index.set(path.basename(f).split('_')[0], f);
  return index;
}

function buildNameIndex(filePath) {
  const map = new Map();
  if (!fs.existsSync(filePath)) return map;
  for (const [key, value] of Object.entries(readJSON(filePath))) {
    const afterColon = key.slice(key.indexOf(':') + 1);
    const dot = afterColon.indexOf('.');
    const refUid = dot === -1 ? afterColon : afterColon.slice(dot + 1);
    map.set(refUid, value.trim());
  }
  return map;
}
function buildBlurbIndex(filePath) {
  const map = new Map();
  if (!fs.existsSync(filePath)) return map;
  for (const [key, value] of Object.entries(readJSON(filePath))) {
    map.set(key.slice(key.indexOf(':') + 1), value.trim());
  }
  return map;
}

function loadSegMap(filePath) {
  if (!filePath || !fs.existsSync(filePath)) return new Map();
  return new Map(Object.entries(readJSON(filePath)));
}

const sujatoManifest = readJSON(path.join(DATA, 'manifest.json'));

console.log('Indexing source files…');
const paliFiles = buildFileIndex(path.join(DATA, 'pali', 'sutta'));
const sujatoFiles = buildFileIndex(path.join(SUJATO, 'sutta'), 'run `npm run update-data:post` first');
const htmlFiles = buildFileIndex(path.join(DATA, 'html', 'pli', 'ms', 'sutta'), 'run `node scripts/fetch-html-structure.mjs` first');
const notesFiles = buildFileIndex(path.join(SUJATO, 'notes'));
console.log(
  `  ${paliFiles.size} pali files, ${sujatoFiles.size} sujato files, ${htmlFiles.size} html structure files, ${notesFiles.size} note files`
);

const nameIndexCache = new Map();
function nameIndexFor(collection) {
  if (nameIndexCache.has(collection)) return nameIndexCache.get(collection);
  const idx = {
    pali: buildNameIndex(path.join(DATA, 'pali', 'name', `${collection}-name_root-misc-site.json`)),
    en: buildNameIndex(path.join(SUJATO, 'name', `${collection}-name_translation-en-sujato.json`)),
  };
  nameIndexCache.set(collection, idx);
  return idx;
}
const blurbIndexCache = new Map();
function blurbIndexFor(collection) {
  if (blurbIndexCache.has(collection)) return blurbIndexCache.get(collection);
  const idx = buildBlurbIndex(path.join(SUJATO, 'blurb', `${collection}-blurbs_root-en.json`));
  blurbIndexCache.set(collection, idx);
  return idx;
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT_TEXT, { recursive: true });
fs.mkdirSync(OUT_SHARDS, { recursive: true });

const suttas = {};
let leafCount = 0;

// Per-uid digests of exactly the bytes written to web/public/data/text/, folded into corpus.json's
// `dataVersion` below. That's what lets a client tell whether the sutta text it cached (under
// unversioned CacheFirst URLs — see CLAUDE.md's cache-staleness note) is still the text this build
// produces, and offer a re-download when it isn't.
const textDigests = new Map();

// Bulk offline download (Settings' "Download all suttas for offline") fetches these shard
// bundles instead of one request per sutta (~4000 across the whole canon) — see
// web/src/lib/offline.ts. Each shard is a hand-built JSON object literal (uid -> that uid's
// already-serialized segment array, string-concatenated rather than re-parsed/re-stringified)
// so building it costs no more than the per-uid file write already does. Flushed once the
// accumulated shard reaches SHARD_TARGET_BYTES, so shard count scales with corpus size rather
// than being fixed.
const SHARD_TARGET_BYTES = 1_000_000;
let shardBuf = [];
let shardBufBytes = 0;
let shardIndex = 0;
const shardManifest = [];

function flushShard() {
  if (shardBuf.length === 0) return;
  const file = `text-shards/${String(shardIndex).padStart(3, '0')}.json`;
  const body = `{${shardBuf.map(([uid, json]) => `${JSON.stringify(uid)}:${json}`).join(',')}}`;
  fs.writeFileSync(path.join(OUT, file), body);
  shardManifest.push({ file, bytes: Buffer.byteLength(body), uids: shardBuf.map(([uid]) => uid) });
  shardIndex += 1;
  shardBuf = [];
  shardBufBytes = 0;
}

function buildLeaf(uid, nodeId, collection) {
  const names = nameIndexFor(collection);
  const blurbs = blurbIndexFor(collection);
  const paliPath = paliFiles.get(uid);
  const sujatoPath = sujatoFiles.get(uid);
  const paliMap = loadSegMap(paliPath);
  const sujatoMap = loadSegMap(sujatoPath);
  const htmlMap = loadSegMap(htmlFiles.get(uid));
  const notesMap = loadSegMap(notesFiles.get(uid));
  const segs = buildBodySegments(paliMap, sujatoMap, htmlMap, notesMap);
  const words = segs.reduce((n, s) => n + (s.en ? s.en.split(/\s+/).filter(Boolean).length : 0), 0);
  const min = Math.max(1, Math.round(words / 200));

  const segsJson = JSON.stringify(
    segs.map(({ key, pali, en, role, headingLevel, note }) => ({
      key,
      pali,
      en,
      ...(role ? { role } : null),
      ...(headingLevel ? { headingLevel } : null),
      ...(note ? { note } : null),
    }))
  );
  fs.writeFileSync(path.join(OUT_TEXT, `${uid}.json`), segsJson);
  textDigests.set(uid, sha256(segsJson));

  shardBuf.push([uid, segsJson]);
  shardBufBytes += Buffer.byteLength(segsJson);
  if (shardBufBytes >= SHARD_TARGET_BYTES) flushShard();

  suttas[uid] = {
    ref: formatRef(uid),
    node: nodeId,
    en: headerTitle(sujatoMap, uid) || stripTitlePrefix(names.en.get(uid)) || formatRef(uid),
    pali: headerTitle(paliMap, uid) || names.pali.get(uid) || formatRef(uid),
    blurb: blurbs.get(uid) || '',
    min,
  };
  leafCount += 1;
}

// Builds category rows (vagga-level) from findLeafGroups() output: one row per category, with
// its member leaves built and its `ref` set to the sutta-range note ("SN35.1–12", "MN1–10")
// rather than a plain ref, since a vagga has no canonical short ref of its own — the range is
// the most useful thing to show. `dotted` selects "{ref}.{n}" (sn/an) vs "{ref}{n}" (mn).
//
// Exception: if there's exactly one category and its label is identical to the *chapter's*
// own label (e.g. SN13 "Comprehension" containing only a single "Comprehension" vagga — the
// vagga name is a pointless restatement of the chapter it's the whole of), that extra nesting
// level is redundant, so it's skipped: returns `undefined` (no `chapters` array, meaning the
// chapter itself becomes the leaf) and tags the leaves with `chapterKey` directly instead of
// the otherwise-identical category key.
function buildCategoryRows(categories, collection, chapterKey, chapterLabel, chapterRef, dotted) {
  const names = nameIndexFor(collection);
  const meta = categories.map(({ key, leaves }) => {
    const paliName = names.pali.get(key);
    return { key, leaves, paliName, label: stripTitlePrefix(names.en.get(key)) || paliName || key };
  });
  if (meta.length === 1 && meta[0].label === chapterLabel) {
    meta[0].leaves.forEach((uid) => buildLeaf(uid, chapterKey, collection));
    return undefined;
  }
  return meta.map(({ key, leaves, label, paliName }) => {
    leaves.forEach((uid) => buildLeaf(uid, key, collection));
    return { id: key, ref: rangeNote(chapterRef, leaves, dotted), label, sub: paliName, count: leaves.length };
  });
}

// Builds one chapter row (sn1, an3, …) from a findChapterNodes() entry: its own ref/label/sub,
// its leaf count, and its vagga-level category rows underneath (buildCategoryRows, with any
// "fifty"/pannasaka wrapper already flattened away by findLeafGroups). Shared by AN (chapters
// sit directly under the nikaya) and SN (chapters sit one level down, under a super-vagga group)
// — the only thing SN's caller does differently is wrap the result in its own group row.
// `labelOverride` covers AN, whose chapter label ("Book of Ones") comes from a hardcoded name
// list rather than the corpus name-index SN's chapters resolve their label from.
function buildChapterRow({ key, node, leaves }, collection, dotted, labelOverride) {
  const names = nameIndexFor(collection);
  const chapterRef = formatRef(key);
  const paliName = names.pali.get(key);
  const chapterLabel = labelOverride ?? (stripTitlePrefix(names.en.get(key)) || paliName || chapterRef);
  const categoryRows = buildCategoryRows(findLeafGroups(node), collection, key, chapterLabel, chapterRef, dotted);
  return { id: key, ref: chapterRef, label: chapterLabel, sub: paliName, count: leaves.length, chapters: categoryRows };
}

const nikayas = [];

// --- DN: flatten straight to leaf suttas, no chapters ---
{
  const leaves = flattenLeaves(loadTree('dn'));
  leaves.forEach((uid) => buildLeaf(uid, 'dn', 'dn'));
  nikayas.push({ id: 'dn', label: NIKAYA_META.dn.label, sub: NIKAYA_META.dn.sub, count: leaves.length });
  console.log(`  dn: ${leaves.length} suttas`);
}

// --- MN: vagga-level categories directly (MN has no numbered-chapter layer of its own), with
// its 3 "fifty" (pannasa) wrapper groups flattened away structurally ---
{
  const categoryRows = buildCategoryRows(findLeafGroups(loadTree('mn')), 'mn', 'mn', NIKAYA_META.mn.label, 'MN', false);
  nikayas.push({ id: 'mn', label: NIKAYA_META.mn.label, sub: NIKAYA_META.mn.sub, count: categoryRows.length, chapters: categoryRows });
  console.log(`  mn: ${categoryRows.length} categories, ${categoryRows.reduce((n, c) => n + c.count, 0)} suttas`);
}

// --- SN: 5 super-vagga groups (Verses, Causation, …), each wrapping its sn1..sn56 chapters;
// each chapter further split into vagga-level categories, with any "fifty" (pannasaka)
// wrapper layer flattened away structurally (see findLeafGroups) rather than shown as a row.
{
  const tree = loadTree('sn');
  const names = nameIndexFor('sn');
  const groupRows = SN_GROUPS.map((group) => {
    const groupNode = findNodeByKey(tree, group.id);
    const chapterNodes = findChapterNodes(groupNode, /^sn\d+$/);
    chapterNodes.sort((a, b) => +a.key.slice(2) - +b.key.slice(2));
    const chapterRows = chapterNodes.map((c) => buildChapterRow(c, 'sn', true));
    const totalSuttas = chapterRows.reduce((n, c) => n + c.count, 0);
    return {
      id: group.id,
      ref: chapterSpanNote('SN', chapterRows[0].id, chapterRows[chapterRows.length - 1].id),
      label: group.label,
      sub: names.pali.get(group.id),
      count: totalSuttas,
      chapters: chapterRows,
    };
  });
  const totalChapters = groupRows.reduce((n, g) => n + g.chapters.length, 0);
  const totalSuttas = groupRows.reduce((n, g) => n + g.count, 0);
  nikayas.push({ id: 'sn', label: NIKAYA_META.sn.label, sub: NIKAYA_META.sn.sub, count: groupRows.length, chapters: groupRows });
  console.log(`  sn: ${groupRows.length} groups, ${totalChapters} chapters, ${totalSuttas} suttas`);
}

// --- AN: nipātas (an1 "Book of Ones", …), each split into vagga-level categories, with any
// "fifty" (pannasaka) wrapper layer flattened away structurally ---
{
  const chapters = findChapterNodes(loadTree('an'), /^an\d+$/);
  chapters.sort((a, b) => +a.key.slice(2) - +b.key.slice(2));
  const chapterRows = chapters.map((c, i) => buildChapterRow(c, 'an', true, `Book of ${AN_BOOK_NAMES[i] || `Book ${i + 1}`}`));
  nikayas.push({ id: 'an', label: NIKAYA_META.an.label, sub: NIKAYA_META.an.sub, count: chapterRows.length, chapters: chapterRows });
  console.log(`  an: ${chapterRows.length} chapters, ${chapterRows.reduce((n, c) => n + c.count, 0)} suttas`);
}

// --- KN: all 20 books, each flattened one level down to its leaf documents ---
{
  const chapterRows = KN_BOOKS.map((book) => {
    const leaves = flattenLeaves(loadTree(book.id));
    leaves.forEach((uid) => buildLeaf(uid, book.id, book.id));
    const ref = REF_ABBR[book.id] || book.id.toUpperCase();
    return { id: book.id, ref, label: book.label, sub: book.pali, count: leaves.length };
  });
  nikayas.push({ id: 'kn', label: NIKAYA_META.kn.label, sub: NIKAYA_META.kn.sub, count: chapterRows.length, chapters: chapterRows });
  console.log(`  kn: ${chapterRows.length} books, ${chapterRows.reduce((n, c) => n + c.count, 0)} leaf documents`);
}

// --- Dictionary: flatten [{entry, definition:[...]}] into a headword-keyed object for O(1) lookup ---
console.log('Building dictionary map…');
const dpdList = readJSON(path.join(DATA, 'pli2en_dpd.json'));
const dpdMap = {};
for (const { entry, definition } of dpdList) dpdMap[entry] = definition;
const dpdJson = JSON.stringify(dpdMap);
fs.writeFileSync(path.join(OUT, 'dictionary.json'), dpdJson);
console.log(`  ${dpdList.length} headwords`);

// Both versions are emitted in corpus.json (precached and revisioned with the app shell, so a new
// build always delivers them) rather than derived from anything the client caches itself. They're
// kept apart because they're separately downloadable and wildly different sizes: a reworded
// sentence in one sutta must not prompt a ~20MB dictionary re-fetch. Sorting by uid makes
// dataVersion independent of directory-walk order, so an unchanged corpus rebuilds identically.
const dataVersion = sha256(
  [...textDigests]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([uid, digest]) => `${uid}:${digest}`)
    .join('\n')
);
const dictionaryVersion = sha256(dpdJson);

fs.writeFileSync(
  path.join(OUT, 'corpus.json'),
  JSON.stringify({ nikayas, suttas, sujatoCommit: sujatoManifest.sourceCommit, dataVersion, dictionaryVersion })
);
console.log(`Wrote corpus.json (${leafCount} leaf documents, ${nikayas.length} nikāyas, data ${dataVersion})`);

flushShard();
const totalShardBytes = shardManifest.reduce((n, s) => n + s.bytes, 0);
fs.writeFileSync(
  path.join(OUT_SHARDS, 'manifest.json'),
  JSON.stringify({ totalBytes: totalShardBytes, totalUids: leafCount, shards: shardManifest })
);
console.log(`Wrote ${shardManifest.length} text shards (${(totalShardBytes / 1e6).toFixed(1)} MB) for offline bulk download`);

console.log('Done.');
