// Query expansion: what readers type, mapped to what this corpus says — see docs/search.md.
//
// Each entry adds an alternative query, never replaces one, so a term that means something in its
// own right keeps its literal results and gains the corpus's wording alongside them.
//
// Two kinds of entry. **Vocabulary** covers words the editorial layer moved away from what readers
// know: the upstream-to-shipped pairs in scripts/update-data/retranslation.mjs are read from the
// reader's side here, so a query for the word Bhikkhu Sujato used reaches the word this app ships.
// **Sutta names** cover a discourse known by a traditional name that is neither its English title
// nor its Pali one.
//
// Keys are written folded — lowercase, no diacritics — because expandQuery is handed a query that
// searchKey has already folded.
//
// An entry fires wherever its key appears, so a key that is part of a longer query substitutes
// into it: "right view" gains "right ditthi" from the `view` entry. Those mixed-language phrases
// match nothing and cost a scan, which is why the table is walked longest key first and why a
// phrase a reader is likely to type whole earns its own entry.
import { searchKey } from './metadata';

interface Expansion {
  // The folded phrase a reader types.
  from: string;
  // The alternative queries it adds, best first.
  to: string[];
}

// Vocabulary. The first group is the retranslated terms, read upstream-to-shipped.
const VOCABULARY: Expansion[] = [
  { from: 'mendicant', to: ['bhikkhu'] },
  { from: 'mendicants', to: ['bhikkhus'] },
  { from: 'immersion', to: ['composure'] },
  { from: 'concentration', to: ['composure'] },
  { from: 'absorption', to: ['jhana'] },
  { from: 'absorptions', to: ['jhanas'] },
  { from: 'textual analysis', to: ['analytical knowledge'] },
  { from: 'mindfulness meditation', to: ['establishment of mindfulness'] },
  { from: 'foundations of mindfulness', to: ['establishments of mindfulness'] },
  { from: 'situational awareness', to: ['attentiveness', 'sampajanna'] },
  { from: 'clear comprehension', to: ['attentiveness', 'sampajanna'] },
  { from: 'origination', to: ['arising', 'samudaya'] },
  { from: 'origin', to: ['arising', 'samudaya'] },
  { from: 'vanishing', to: ['passing away', 'vaya'] },
  { from: 'rise and fall', to: ['arising and passing away', 'udayabbaya'] },
  { from: 'perishing', to: ['passing away'] },
  { from: 'anxiety', to: ['agitation', 'paritassana'] },
  { from: 'placing the mind', to: ['thought', 'vitakka'] },
  { from: 'keeping it connected', to: ['examination', 'vicara'] },
  { from: 'rational application of mind', to: ['proper attention', 'yoniso'] },
  { from: 'wise attention', to: ['proper attention', 'yoniso'] },
  { from: 'choices', to: ['sankhara'] },
  { from: 'formations', to: ['sankhara'] },
  { from: 'volitional formations', to: ['sankhara'] },
  { from: 'mental fabrications', to: ['sankhara'] },
  // Terms readers know from other translations and from ordinary Buddhist English, which this
  // corpus spells another way. A word this corpus already uses gets no entry: it would only add
  // the noise of a second query for nothing.
  { from: 'loving-kindness', to: ['love', 'metta'] },
  { from: 'loving kindness', to: ['love', 'metta'] },
  { from: 'metta', to: ['love'] },
  { from: 'enlightenment', to: ['awakening'] },
  { from: 'enlightened', to: ['awakened'] },
  { from: 'nibbana', to: ['extinguishment'] },
  { from: 'nirvana', to: ['extinguishment', 'nibbana'] },
  { from: 'karma', to: ['deeds', 'kamma'] },
  { from: 'arahant', to: ['perfected'] },
  { from: 'arahants', to: ['perfected'] },
  { from: 'luminous', to: ['radiant'] },
  { from: 'not-self', to: ['not self', 'anatta'] },
  { from: 'taints', to: ['defilements'] },
  { from: 'sotapanna', to: ['stream-enterer'] },
  { from: 'mindfulness of breathing', to: ['anapanassati'] },
  { from: 'anapanasati', to: ['anapanassati'] },

  // The people of the canon. This corpus says bhikkhu, and the reader's own word for one is
  // "monk" as often as anything a translation uses.
  { from: 'monk', to: ['bhikkhu'] },
  { from: 'monks', to: ['bhikkhus'] },
  { from: 'nun', to: ['bhikkhuni'] },
  { from: 'nuns', to: ['bhikkhunis'] },
  { from: 'monastic', to: ['bhikkhu'] },
  { from: 'monastics', to: ['bhikkhus'] },
  { from: 'tathagata', to: ['realized one'] },
  { from: 'blessed one', to: ['buddha', 'bhagava'] },
  { from: 'world-honoured one', to: ['buddha'] },
  { from: 'world-honored one', to: ['buddha'] },
  { from: 'fortunate one', to: ['buddha', 'bhagava'] },
  { from: 'sakyamuni', to: ['sakyan', 'gotama'] },
  { from: 'worldling', to: ['ordinary person', 'puthujjana'] },
  { from: 'lay disciple', to: ['lay follower', 'upasaka'] },
  { from: 'layman', to: ['lay follower', 'upasaka'] },
  { from: 'laywoman', to: ['lay follower', 'upasika'] },
  { from: 'jains', to: ['jain', 'nigantha'] },
  { from: 'niganthas', to: ['jain', 'nigantha'] },
  { from: 'naga', to: ['dragon'] },
  { from: 'nagas', to: ['dragons'] },
  { from: 'yakkha', to: ['native spirit'] },
  { from: 'yakkhas', to: ['native spirits'] },
  { from: 'gandhabba', to: ['centaur'] },
  { from: 'asura', to: ['titan'] },
  { from: 'asuras', to: ['titans'] },
  { from: 'deity', to: ['god', 'deva'] },
  { from: 'deities', to: ['gods', 'deva'] },
  { from: 'brahma', to: ['divinity'] },
  { from: 'hungry ghost', to: ['ghost', 'peta'] },
  { from: 'hungry ghosts', to: ['ghosts', 'peta'] },
  { from: 'hell realm', to: ['hell', 'niraya'] },
  { from: 'heavenly realm', to: ['heaven', 'sagga'] },

  // Ordinary Buddhist English, and the words other translations use, read against what this
  // corpus says. The Pali follows the English wherever the term of art is the stable one.
  { from: 'wholesome', to: ['skillful', 'kusala'] },
  { from: 'unwholesome', to: ['unskillful', 'akusala'] },
  { from: 'skilful', to: ['skillful', 'kusala'] },
  { from: 'unskilful', to: ['unskillful', 'akusala'] },
  { from: 'stress', to: ['suffering', 'dukkha'] },
  { from: 'unsatisfactoriness', to: ['suffering', 'dukkha'] },
  { from: 'suffering', to: ['dukkha'] },
  { from: 'impermanence', to: ['anicca'] },
  { from: 'impermanent', to: ['anicca'] },
  { from: 'non-self', to: ['not-self', 'anatta'] },
  { from: 'no self', to: ['not-self', 'anatta'] },
  { from: 'egolessness', to: ['not-self', 'anatta'] },
  { from: 'soul', to: ['self', 'atta'] },
  { from: 'thirst', to: ['craving', 'tanha'] },
  { from: 'craving', to: ['tanha'] },
  { from: 'clinging', to: ['grasping', 'upadana'] },
  { from: 'attachment', to: ['grasping', 'upadana'] },
  { from: 'aversion', to: ['hate', 'dosa'] },
  { from: 'hatred', to: ['hate', 'dosa'] },
  { from: 'ill-will', to: ['ill will', 'byapada'] },
  { from: 'anger', to: ['kodha'] },
  { from: 'pride', to: ['conceit', 'mana'] },
  { from: 'ignorance', to: ['avijja'] },
  { from: 'delusion', to: ['moha'] },
  { from: 'greed', to: ['lobha'] },
  { from: 'cankers', to: ['defilements', 'asava'] },
  { from: 'effluents', to: ['defilements', 'asava'] },
  { from: 'influxes', to: ['defilements', 'asava'] },
  { from: 'outflows', to: ['defilements', 'asava'] },
  { from: 'fermentations', to: ['defilements', 'asava'] },
  { from: 'defilements', to: ['asava'] },
  { from: 'corruptions', to: ['upakkilesa'] },
  { from: 'fetters', to: ['samyojana'] },
  { from: 'hindrances', to: ['nivarana'] },
  { from: 'five hindrances', to: ['hindrances', 'nivarana'] },
  { from: 'sloth and torpor', to: ['dullness and drowsiness', 'thinamiddha'] },
  { from: 'sloth', to: ['dullness', 'thina'] },
  { from: 'torpor', to: ['drowsiness', 'middha'] },
  { from: 'restlessness and remorse', to: ['uddhaccakukkucca'] },
  { from: 'sceptical doubt', to: ['doubt', 'vicikiccha'] },
  { from: 'skeptical doubt', to: ['doubt', 'vicikiccha'] },
  { from: 'sensual desire', to: ['kamacchanda'] },
  { from: 'sense desire', to: ['sensual desire', 'kamacchanda'] },
  { from: 'sense pleasures', to: ['sensual pleasures', 'kama'] },
  { from: 'aggregates', to: ['khandha'] },
  { from: 'five aggregates', to: ['aggregates', 'khandha'] },
  { from: 'heaps', to: ['aggregates', 'khandha'] },
  { from: 'sense bases', to: ['sense fields', 'ayatana'] },
  { from: 'six sense bases', to: ['sense fields', 'ayatana'] },
  { from: 'elements', to: ['dhatu'] },
  { from: 'name-and-form', to: ['name and form', 'namarupa'] },
  { from: 'mentality-materiality', to: ['name and form', 'namarupa'] },
  { from: 'becoming', to: ['continued existence', 'bhava'] },
  { from: 'existence', to: ['continued existence', 'bhava'] },
  { from: 'birth', to: ['rebirth', 'jati'] },
  { from: 'ageing and death', to: ['old age and death', 'jaramarana'] },
  { from: 'aging and death', to: ['old age and death', 'jaramarana'] },
  { from: 'twelve links', to: ['dependent origination', 'paticcasamuppada'] },
  { from: 'conditioned arising', to: ['dependent origination', 'paticcasamuppada'] },
  { from: 'conditionality', to: ['dependent origination', 'paticcasamuppada'] },
  { from: 'dependent origination', to: ['dependent arising', 'paticcasamuppada'] },
  { from: 'cessation', to: ['nirodha'] },
  { from: 'round of rebirths', to: ['transmigration', 'samsara'] },
  { from: 'cycle of rebirth', to: ['transmigration', 'samsara'] },
  { from: 'samsara', to: ['transmigration'] },
  { from: 'deathless', to: ['amata'] },
  { from: 'the unconditioned', to: ['unconditioned', 'asankhata'] },
  { from: 'emptiness', to: ['sunnata'] },
  { from: 'parinibbana', to: ['full extinguishment'] },
  { from: 'final nibbana', to: ['full extinguishment', 'parinibbana'] },
  { from: 'disenchantment', to: ['disillusionment', 'nibbida'] },
  { from: 'revulsion', to: ['disillusionment', 'nibbida'] },
  { from: 'dispassion', to: ['fading away', 'viraga'] },
  { from: 'relinquishment', to: ['letting go', 'patinissagga'] },
  { from: 'liberation', to: ['freedom', 'vimutti'] },
  { from: 'release', to: ['freedom', 'vimutti'] },
  { from: 'emancipation', to: ['freedom', 'vimutti'] },
  { from: 'volition', to: ['intention', 'cetana'] },
  { from: 'volitions', to: ['intentions', 'cetana'] },
  { from: 'kammic result', to: ['result of deeds', 'vipaka'] },
  { from: 'vipaka', to: ['result of deeds'] },
  { from: 'merit', to: ['punna'] },
  { from: 'morality', to: ['ethics', 'sila'] },
  { from: 'virtue', to: ['ethics', 'sila'] },
  { from: 'moral conduct', to: ['ethics', 'sila'] },
  { from: 'precepts', to: ['sikkhapada'] },
  { from: 'five precepts', to: ['precepts', 'training rules'] },
  { from: 'eight precepts', to: ['precepts', 'sabbath'] },
  { from: 'uposatha', to: ['sabbath'] },
  { from: 'generosity', to: ['giving', 'dana'] },
  { from: 'charity', to: ['giving', 'dana'] },
  { from: 'dana', to: ['giving'] },
  { from: 'renunciation', to: ['nekkhamma'] },
  { from: 'seclusion', to: ['viveka'] },
  { from: 'solitude', to: ['seclusion', 'viveka'] },
  { from: 'patience', to: ['khanti'] },
  { from: 'faith', to: ['saddha'] },
  { from: 'confidence', to: ['faith', 'saddha'] },
  { from: 'energy', to: ['viriya'] },
  { from: 'heedfulness', to: ['diligence', 'appamada'] },
  { from: 'vigilance', to: ['diligence', 'appamada'] },
  { from: 'diligence', to: ['appamada'] },
  { from: 'wisdom', to: ['panna'] },
  { from: 'discernment', to: ['wisdom', 'panna'] },
  { from: 'insight', to: ['vipassana'] },
  { from: 'serenity', to: ['samatha'] },
  { from: 'tranquillity', to: ['serenity', 'samatha'] },
  { from: 'tranquility', to: ['serenity', 'samatha'] },
  { from: 'calm abiding', to: ['serenity', 'samatha'] },
  { from: 'samatha', to: ['serenity'] },
  { from: 'samadhi', to: ['composure'] },
  { from: 'one-pointedness', to: ['unified', 'ekaggata'] },
  { from: 'rapture', to: ['piti'] },
  { from: 'equanimity', to: ['upekkha'] },
  { from: 'compassion', to: ['karuna'] },
  { from: 'sympathetic joy', to: ['rejoicing', 'mudita'] },
  { from: 'altruistic joy', to: ['rejoicing', 'mudita'] },
  { from: 'appreciative joy', to: ['rejoicing', 'mudita'] },
  { from: 'divine abidings', to: ['divine meditations', 'brahmavihara'] },
  { from: 'divine abiding', to: ['divine meditation', 'brahmavihara'] },
  { from: 'brahmavihara', to: ['divine meditation', 'love'] },
  { from: 'brahmaviharas', to: ['divine meditations', 'love'] },
  { from: 'four immeasurables', to: ['immeasurables', 'appamanna'] },
  { from: 'mindfulness', to: ['sati'] },
  { from: 'contemplation of the body', to: ['mindfulness of the body', 'kayagatasati'] },
  { from: 'body scan', to: ['mindfulness of the body', 'kayagatasati'] },
  { from: 'breath meditation', to: ['mindfulness of breathing', 'anapanassati'] },
  { from: 'breathing meditation', to: ['mindfulness of breathing', 'anapanassati'] },
  { from: 'anapana', to: ['anapanassati'] },
  { from: 'loving-kindness meditation', to: ['meditation on love', 'metta'] },
  { from: 'foulness', to: ['ugliness', 'asubha'] },
  { from: 'loathsomeness', to: ['ugliness', 'asubha'] },
  { from: 'corpse contemplation', to: ['charnel ground', 'asubha'] },
  { from: 'meditation object', to: ['meditation subject'] },
  { from: 'kasina', to: ['universal dimension'] },
  { from: 'kasinas', to: ['universal dimensions'] },
  { from: 'recollections', to: ['anussati'] },
  { from: 'mindfulness of death', to: ['maranassati'] },
  { from: 'awakening factors', to: ['bojjhanga'] },
  { from: 'enlightenment factors', to: ['awakening factors', 'bojjhanga'] },
  { from: 'factors of enlightenment', to: ['awakening factors', 'bojjhanga'] },
  { from: 'factors of awakening', to: ['awakening factors', 'bojjhanga'] },
  { from: 'seven factors of awakening', to: ['awakening factors', 'bojjhanga'] },
  { from: 'four right efforts', to: ['right efforts', 'sammappadhana'] },
  { from: 'right exertion', to: ['right effort', 'sammappadhana'] },
  { from: 'bases of psychic power', to: ['psychic power', 'iddhipada'] },
  { from: 'spiritual faculties', to: ['faculties', 'indriya'] },
  { from: 'five faculties', to: ['faculties', 'indriya'] },
  { from: 'five powers', to: ['powers', 'bala'] },
  { from: 'requisites of awakening', to: ['bodhipakkhiya'] },
  { from: 'thirty-seven factors', to: ['bodhipakkhiya'] },
  { from: 'right intention', to: ['right thought', 'sammasankappa'] },
  { from: 'right concentration', to: ['right composure', 'sammasamadhi'] },
  { from: 'right immersion', to: ['right composure', 'sammasamadhi'] },
  { from: 'eightfold path', to: ['atthangika'] },
  { from: 'path factor', to: ['atthangika'] },
  { from: 'middle way', to: ['majjhima patipada'] },
  { from: 'middle path', to: ['middle way', 'majjhima patipada'] },
  { from: 'noble truths', to: ['ariyasacca'] },
  { from: 'four noble truths', to: ['ariyasacca', 'noble truth'] },
  { from: 'supernormal powers', to: ['psychic powers', 'iddhi'] },
  { from: 'higher knowledges', to: ['direct knowledge', 'abhinna'] },
  { from: 'direct knowledge', to: ['abhinna'] },
  { from: 'divine eye', to: ['clairvoyance', 'dibbacakkhu'] },
  { from: 'divine ear', to: ['clairaudience'] },
  { from: 'three knowledges', to: ['tevijja'] },
  { from: 'past lives', to: ['recollection of past lives'] },
  { from: 'stream entry', to: ['stream-enterer', 'sotapatti'] },
  { from: 'stream-entry', to: ['stream-enterer', 'sotapatti'] },
  { from: 'stream winner', to: ['stream-enterer', 'sotapanna'] },
  { from: 'once returner', to: ['once-returner', 'sakadagami'] },
  { from: 'once-returner', to: ['sakadagami'] },
  { from: 'non returner', to: ['non-returner', 'anagami'] },
  { from: 'non-returner', to: ['anagami'] },
  { from: 'trainee', to: ['sekha'] },
  { from: 'fully enlightened', to: ['fully awakened'] },
  { from: 'self-awakened', to: ['awakened', 'sambuddha'] },
  { from: 'bodhisattva', to: ['bodhisatta'] },
  { from: 'view', to: ['ditthi'] },
  { from: 'wrong view', to: ['micchaditthi'] },
  { from: 'right view', to: ['sammaditthi'] },
  { from: 'conceit', to: ['mana'] },
  { from: 'doubt', to: ['vicikiccha'] },
  { from: 'jealousy', to: ['issa'] },
  { from: 'stinginess', to: ['macchariya'] },
  { from: 'proliferation', to: ['papanca'] },
  { from: 'sign', to: ['nimitta'] },
  { from: 'signless', to: ['animitta'] },
  { from: 'consciousness', to: ['vinnana'] },
  { from: 'perception', to: ['sanna'] },
  { from: 'feeling', to: ['vedana'] },
  { from: 'contact', to: ['phassa'] },
  { from: 'sensation', to: ['feeling', 'vedana'] },
  { from: 'form', to: ['rupa'] },
  { from: 'materiality', to: ['form', 'rupa'] },
  { from: 'mind', to: ['citta'] },
  { from: 'the teaching', to: ['dhamma'] },
  { from: 'monastery', to: ['vihara'] },
  { from: 'alms round', to: ['almsround'] },
  { from: 'forest dwelling', to: ['wilderness'] },
];

// Sutta names — a discourse as readers name it to each other.
const SUTTA_NAMES: Expansion[] = [
  { from: 'the fire sermon', to: ['burning'] },
  { from: 'fire sermon', to: ['burning'] },
  { from: 'sigalovada', to: ['advice to sigalaka'] },
  { from: 'karaniya metta', to: ['discourse on love'] },
  { from: 'karaniyametta', to: ['discourse on love'] },
  { from: 'honeyball', to: ['the honey-cake'] },
  { from: 'honey ball', to: ['the honey-cake'] },
  { from: 'ant-hill', to: ['termite mound'] },
  { from: 'anthill', to: ['termite mound'] },
  { from: 'ants nest', to: ['termite mound'] },
  { from: "ant's nest", to: ['termite mound'] },
  { from: 'water snake', to: ['cobra'] },
  { from: 'poisoned arrow', to: ['arrow smeared with poison'] },
  { from: 'turning the wheel of dhamma', to: ['rolling forth the wheel of dhamma'] },
  { from: 'setting in motion the wheel of dhamma', to: ['rolling forth the wheel of dhamma'] },
  { from: 'discourse on the not-self characteristic', to: ['the characteristic of not-self'] },
  { from: 'satipatthana', to: ['establishment of mindfulness'] },
  { from: 'mahasatipatthana', to: ['establishment of mindfulness'] },

  // A discourse by its Pali name, where that name is not the Pali title this corpus carries.
  { from: 'kalama sutta', to: ['with the kalamas', 'kesamutti'] },
  { from: 'kalama', to: ['kalamas'] },
  { from: 'metta sutta', to: ['discourse on love'] },
  { from: 'mangala sutta', to: ['blessings', 'mangala'] },
  { from: 'ratana sutta', to: ['gems', 'ratana'] },
  { from: 'jewel discourse', to: ['gems', 'ratana'] },
  { from: 'dhammacakka', to: ['rolling forth the wheel of dhamma'] },
  { from: 'dhammacakkappavattana', to: ['rolling forth the wheel of dhamma'] },
  { from: 'first sermon', to: ['rolling forth the wheel of dhamma'] },
  { from: 'anattalakkhana', to: ['the characteristic of not-self'] },
  { from: 'anatta lakkhana', to: ['the characteristic of not-self'] },
  { from: 'adittapariyaya', to: ['burning'] },
  { from: 'aditta', to: ['burning'] },
  { from: 'alagaddupama', to: ['the simile of the cobra'] },
  { from: 'snake simile', to: ['the simile of the cobra'] },
  { from: 'simile of the snake', to: ['the simile of the cobra'] },
  { from: 'vammika', to: ['termite mound'] },
  { from: 'madhupindika', to: ['the honey-cake'] },
  { from: 'culamalunkya', to: ['the shorter discourse with malunkya'] },
  { from: 'cula malunkyaputta', to: ['the shorter discourse with malunkya'] },
  { from: 'arrow simile', to: ['arrow smeared with poison'] },
  { from: 'simile of the arrow', to: ['arrow smeared with poison'] },
  { from: 'kakacupama', to: ['the simile of the saw'] },
  { from: 'vatthupama', to: ['the simile of the cloth'] },
  { from: 'phenapindupama', to: ['foam'] },
  { from: 'foam simile', to: ['lump of foam'] },
  { from: 'agganna', to: ['what came first'] },
  { from: 'mahanidana', to: ['the great discourse on causation'] },
  { from: 'great discourse on causation', to: ['mahanidana'] },
  { from: 'mahaparinibbana', to: ['the great discourse on the buddha’s extinguishment'] },
  { from: 'sallekha', to: ['effacement'] },
  { from: 'kaccayanagotta', to: ['kaccanagotta'] },
  { from: 'kaccana', to: ['kaccanagotta'] },
  { from: 'bhaddekaratta', to: ['one fine night'] },
  { from: 'khaggavisana', to: ['horned rhino'] },
  { from: 'rhinoceros', to: ['horned rhino', 'khaggavisana'] },
  { from: 'rhinoceros horn', to: ['horned rhino', 'khaggavisana'] },
  { from: 'parayana', to:['the way to the far shore'] },
  { from: 'bhayabherava', to: ['fear and dread'] },
  { from: 'dvedhavitakka', to: ['two kinds of thought'] },
  { from: 'ambalatthika rahulovada', to: ['advice to rahula'] },
  { from: 'rahulovada', to: ['advice to rahula'] },
  { from: 'sigalaka', to: ['advice to sigalaka'] },
  { from: 'anathapindikovada', to: ['advice to anathapindika'] },
  { from: 'cakkavattisihanada', to: ['the wheel-turning monarch'] },
  { from: 'tevijja sutta', to: ['the three knowledges'] },
  { from: 'potthapada', to: ['with potthapada'] },
  { from: 'kevatta', to: ['with kevaddha'] },
  { from: 'kevaddha', to: ['with kevaddha'] },
  { from: 'kutadanta', to: ['with kutadanta'] },
  { from: 'sonadanda', to: ['with sonadanda'] },
  { from: 'samannaphala', to: ['the fruits of the ascetic life'] },
  { from: 'brahmajala', to: ['the divine net'] },
  { from: 'ariyapariyesana', to: ['the noble quest'] },
  { from: 'noble search', to: ['the noble quest'] },
  { from: 'anapanasati sutta', to: ['mindfulness of breathing', 'anapanassati'] },
  { from: 'kayagatasati', to: ['mindfulness of the body'] },
  { from: 'culahatthipadopama', to: ['the shorter simile of the elephant’s footprint'] },
  { from: 'mahahatthipadopama', to: ['the longer simile of the elephant’s footprint'] },
  { from: 'elephant footprint', to: ['elephant’s footprint'] },
  { from: 'vajira', to: ['with vajira'] },
  { from: 'chariot simile', to: ['with vajira'] },
  { from: 'bahiya', to: ['with bahiya'] },
  { from: 'angulimala', to:['with angulimala'] },
  { from: 'blind men and the elephant', to: ['nanatitthiya'] },
  { from: 'simile of the lute', to: ['the harp'] },
  { from: 'parable of the raft', to: ['simile of the raft'] },
  { from: 'burning house', to: ['burning'] },
  { from: 'salt crystal', to: ['a lump of salt'] },
  { from: 'simsapa', to: ['rosewood forest', 'sisapavana'] },
  { from: 'handful of leaves', to: ['rosewood forest', 'sisapavana'] },
];

// The table expandQuery walks, longest key first so the entry matching most of the query takes the
// slots before a single word inside it does. The sort is stable, so entries of equal key length
// keep the order they are written in and the `to` lists stay best-first.
export const QUERY_EXPANSIONS: Expansion[] = [...VOCABULARY, ...SUTTA_NAMES]
  .map(({ from, to }) => ({ from: searchKey(from), to: to.map(searchKey) }))
  .sort((a, b) => b.from.length - a.from.length);

const RE_ESCAPE = /[.*+?^${}()|[\]\\]/g;

// Matches an entry's phrase as whole words. `\b` is ASCII-only and would break on a Pali key, so
// the boundaries are the same lookarounds the matcher uses.
function phraseRe(from: string): RegExp {
  return new RegExp(`(?<!\\p{L})${from.replace(RE_ESCAPE, '\\$&')}(?!\\p{L})`, 'u');
}

// How many alternatives one query may add. Each costs a scan of both blobs, and past a handful the
// results stop being about what was typed.
export const MAX_EXPANSIONS = 4;

// The alternative queries `q` adds, `q` itself excluded. `q` must already be folded by searchKey.
export function expandQuery(q: string, limit = MAX_EXPANSIONS): string[] {
  const out: string[] = [];
  const matched: string[] = [];
  for (const { from, to } of QUERY_EXPANSIONS) {
    // The pattern is the key itself between two boundaries, so a query not containing the key
    // cannot match it. Checked before the regex, which is otherwise compiled for all 363 entries
    // on every keystroke.
    if (!q.includes(from)) continue;
    // A key inside a key that has already matched names the same part of the query, less
    // precisely: "hindrances" under "five hindrances". Substituting it there only produces the
    // half-replaced phrase the longer entry exists to avoid.
    if (matched.some((m) => m.includes(from))) continue;
    const re = phraseRe(from);
    if (!re.test(q)) continue;
    matched.push(from);
    for (const alt of to) {
      const expanded = q.replace(re, alt).replace(/\s+/g, ' ').trim();
      if (expanded && expanded !== q && !out.includes(expanded)) out.push(expanded);
      if (out.length >= limit) return out;
    }
  }
  return out;
}
